config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :avaliacao_festa
  resources :avaliacao_baladas
  resources :usuarios
  resources :festa
  resources :baladas
  resources :cadastros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'festa#index'
  get '/administrador', to: 'administrador#show'
  resources :administradors
  resources :festas
  get '/gambeta', to: 'gambeta#show'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post 'checkin', to: 'checkin#new'
  delete 'checkin_delete', to: 'checkin#destroy'

  get 'search', to: 'festa#search'

  post 'avaliar_festa', to: 'avaliacao_festa#create'
  get 'excluir_aval_festa/:id', to: 'avaliacao_festa#excluir'
end

app/models/administrador.rb
class Administrador < ActiveRecord::Base
  attr_accessor :current
  @connection = ActiveRecord::Base.establish_connection
  self.table_name = 'Administrador'
  # belongs_to:
  # has_many:
end

app/controllers/administrador_controller.rb
class AdministradorController < ActionController::Base
  def show
    # @a = ActiveRecord::Base.connection.tables
    @connection = ActiveRecord::Base.establish_connection(adapter: 'mysql2',
                                                        encoding: 'utf8',
                                                        pool: 5,
                                                        timeout: 5000,
                                                        database: 'inclub',
                                                        username: 'root',
                                                        password: "ach20252017",
                                                        host: '35.184.66.35',
                                                        port: 3306)
    # @a = Administrador

    Faker::Config.locale = 'pt-BR'

    # sql = "SELECT * from EstiloBalada;"
    # @result = @connection.connection.execute(sql)

# CREATE TABLE `AvaliacaoBalada` (
#   `idAvaliacao` int(11) NOT NULL AUTO_INCREMENT,
#   `idBalada` int(11) DEFAULT NULL,
#   `idUsuario` int(11) DEFAULT NULL,
#   `comentario` varchar(45) DEFAULT NULL,
#   `nota` varchar(45) DEFAULT NULL,
#   `dataHora` datetime DEFAULT NULL,
#   PRIMARY KEY (`idAvaliacao`),
#   KEY `fkBalada_idx` (`idBalada`),
#   KEY `fkUsuario_idx` (`idUsuario`),
#   CONSTRAINT `fkBalada` FOREIGN KEY (`idBalada`) REFERENCES `Balada` (`idCadastro`) ON DELETE NO ACTION ON UPDATE NO ACTION,
#   CONSTRAINT `fkUsuario2` FOREIGN KEY (`idUsuario`) REFERENCES `Usuario` (`idCadastro`) ON DELETE NO ACTION ON UPDATE NO ACTION
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8

# CREATE TABLE `CheckIn` (
#   `idCheckIn` int(11) NOT NULL AUTO_INCREMENT,
#   `idUsuario` int(11) DEFAULT NULL,
#   `idFesta` int(11) DEFAULT NULL,
#   `dataHora` datetime DEFAULT NULL,
#   PRIMARY KEY (`idCheckIn`),
#   KEY `idCadastro_idx` (`idUsuario`),
#   KEY `idFesta_idx` (`idFesta`),
#   CONSTRAINT `fkCadastro2` FOREIGN KEY (`idUsuario`) REFERENCES `Usuario` (`idCadastro`) ON DELETE NO ACTION ON UPDATE NO ACTION,
#   CONSTRAINT `fkFesta2` FOREIGN KEY (`idFesta`) REFERENCES `Festa` (`idFesta`) ON DELETE NO ACTION ON UPDATE NO ACTION
# ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    # 15.times do |n|
    #   @idFesta = rand(1..150)
    #   10.times do |n|
    #     @idUsuario = rand(16..1000)
    #     @dataHora = Faker::Time.between(10.days.from_now, 30.days.from_now).to_formatted_s(:db)
    #     sql = "INSERT INTO CheckIn(idFesta, idUsuario, dataHora)
    #                               VALUES (#{@idFesta}, #{@idUsuario}, '#{@dataHora}');"
    #     @result = @connection.connection.insert(sql)
    #   end
    # end

    # sql = "SELECT * from Festa"
    # @result = @connection.connection.execute(sql)
    # puts @result
    # puts 'PUTS'
    # puts @result.first
    # puts 'PUTS'
  end
end

app/controllers/administradors_controller.rb
class AdministradorsController < ApplicationController
  before_action :set_administrador, only: [:show, :edit, :update, :destroy]

  # GET /administradors
  # GET /administradors.json
  def index
    @administradors = Administrador.all
  end

  # GET /administradors/1
  # GET /administradors/1.json
  def show
  end

  # GET /administradors/new
  def new
    @administrador = Administrador.new
  end

  # GET /administradors/1/edit
  def edit
  end

  # POST /administradors
  # POST /administradors.json
  def create
    @administrador = Administrador.new(administrador_params)

    respond_to do |format|
      if @administrador.save
        format.html { redirect_to @administrador, notice: 'Administrador was successfully created.' }
        format.json { render :show, status: :created, location: @administrador }
      else
        format.html { render :new }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradors/1
  # PATCH/PUT /administradors/1.json
  def update
    respond_to do |format|
      if @administrador.update(administrador_params)
        format.html { redirect_to @administrador, notice: 'Administrador was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrador }
      else
        format.html { render :edit }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradors/1
  # DELETE /administradors/1.json
  def destroy
    @administrador.destroy
    respond_to do |format|
      format.html { redirect_to administradors_url, notice: 'Administrador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrador
      @administrador = Administrador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrador_params
      params.fetch(:administrador, {})
    end
end

app/helpers/administrador_helper.rb
module AdministradorHelper
end

app/helpers/administradors_helper.rb
module AdministradorsHelper
end

app/views/administradors/_form.html.erb
<%= form_for(administrador) do |f| %>
  <% if administrador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrador.errors.count, "error") %> prohibited this administrador from being saved:</h2>

      <ul>
      <% administrador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/administradors/edit.html.erb
<h1>Editing Administrador</h1>

<%= render 'form', administrador: @administrador %>

<%= link_to 'Show', @administrador %> |
<%= link_to 'Back', administradors_path %>

app/views/administradors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administradors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administradors.each do |administrador| %>
      <tr>
        <td><%= link_to 'Show', administrador %></td>
        <td><%= link_to 'Edit', edit_administrador_path(administrador) %></td>
        <td><%= link_to 'Destroy', administrador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrador', new_administrador_path %>

app/views/administradors/new.html.erb
<h1>New Administrador</h1>

<%= render 'form', administrador: @administrador %>

<%= link_to 'Back', administradors_path %>

app/views/administradors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_administrador_path(@administrador) %> |
<%= link_to 'Back', administradors_path %>