config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :avaliacao_festa
  resources :avaliacao_baladas
  resources :usuarios
  resources :festa
  resources :baladas
  resources :cadastros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'festa#index'
  get '/administrador', to: 'administrador#show'
  resources :administradors
  resources :festas
  get '/gambeta', to: 'gambeta#show'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post 'checkin', to: 'checkin#new'
  delete 'checkin_delete', to: 'checkin#destroy'

  get 'search', to: 'festa#search'

  post 'avaliar_festa', to: 'avaliacao_festa#create'
  get 'excluir_aval_festa/:id', to: 'avaliacao_festa#excluir'
end

app/models/avaliacao_balada.rb
class AvaliacaoBalada < ActiveRecord::Base
  attr_accessor :current
  @connection = ActiveRecord::Base.establish_connection
  self.table_name = 'AvaliacaoBalada'
  belongs_to :cadastro
  # has_many:
end

app/controllers/avaliacao_baladas_controller.rb
class AvaliacaoBaladasController < ApplicationController
  before_action :set_avaliacao_balada, only: [:show, :edit, :update, :destroy]

  # GET /avaliacao_baladas
  # GET /avaliacao_baladas.json
  def index
    @avaliacao_baladas = AvaliacaoBalada.all
  end

  # GET /avaliacao_baladas/1
  # GET /avaliacao_baladas/1.json
  def show
  end

  # GET /avaliacao_baladas/new
  def new
    @avaliacao_balada = AvaliacaoBalada.new
  end

  # GET /avaliacao_baladas/1/edit
  def edit
  end

  # POST /avaliacao_baladas
  # POST /avaliacao_baladas.json
  def create
    @avaliacao_balada = AvaliacaoBalada.new(avaliacao_balada_params)

    respond_to do |format|
      if @avaliacao_balada.save
        format.html { redirect_to @avaliacao_balada, notice: 'Avaliacao balada was successfully created.' }
        format.json { render :show, status: :created, location: @avaliacao_balada }
      else
        format.html { render :new }
        format.json { render json: @avaliacao_balada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avaliacao_baladas/1
  # PATCH/PUT /avaliacao_baladas/1.json
  def update
    respond_to do |format|
      if @avaliacao_balada.update(avaliacao_balada_params)
        format.html { redirect_to @avaliacao_balada, notice: 'Avaliacao balada was successfully updated.' }
        format.json { render :show, status: :ok, location: @avaliacao_balada }
      else
        format.html { render :edit }
        format.json { render json: @avaliacao_balada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avaliacao_baladas/1
  # DELETE /avaliacao_baladas/1.json
  def destroy
    @avaliacao_balada.destroy
    respond_to do |format|
      format.html { redirect_to avaliacao_baladas_url, notice: 'Avaliacao balada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avaliacao_balada
      @avaliacao_balada = AvaliacaoBalada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def avaliacao_balada_params
      params.fetch(:avaliacao_balada, {})
    end
end

app/helpers/avaliacao_baladas_helper.rb
module AvaliacaoBaladasHelper
end

app/views/avaliacao_baladas/_form.html.erb
<%= form_for(avaliacao_balada) do |f| %>
  <% if avaliacao_balada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(avaliacao_balada.errors.count, "error") %> prohibited this avaliacao_balada from being saved:</h2>

      <ul>
      <% avaliacao_balada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/avaliacao_baladas/edit.html.erb
<h1>Editing Avaliacao Balada</h1>

<%= render 'form', avaliacao_balada: @avaliacao_balada %>

<%= link_to 'Show', @avaliacao_balada %> |
<%= link_to 'Back', avaliacao_baladas_path %>

app/views/avaliacao_baladas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Avaliacao Baladas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @avaliacao_baladas.each do |avaliacao_balada| %>
      <tr>
        <td><%= link_to 'Show', avaliacao_balada %></td>
        <td><%= link_to 'Edit', edit_avaliacao_balada_path(avaliacao_balada) %></td>
        <td><%= link_to 'Destroy', avaliacao_balada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Avaliacao Balada', new_avaliacao_balada_path %>

app/views/avaliacao_baladas/new.html.erb
<h1>New Avaliacao Balada</h1>

<%= render 'form', avaliacao_balada: @avaliacao_balada %>

<%= link_to 'Back', avaliacao_baladas_path %>

app/views/avaliacao_baladas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_avaliacao_balada_path(@avaliacao_balada) %> |
<%= link_to 'Back', avaliacao_baladas_path %>