config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :avaliacao_festa
  resources :avaliacao_baladas
  resources :usuarios
  resources :festa
  resources :baladas
  resources :cadastros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'festa#index'
  get '/administrador', to: 'administrador#show'
  resources :administradors
  resources :festas
  get '/gambeta', to: 'gambeta#show'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  post 'checkin', to: 'checkin#new'
  delete 'checkin_delete', to: 'checkin#destroy'

  get 'search', to: 'festa#search'

  post 'avaliar_festa', to: 'avaliacao_festa#create'
  get 'excluir_aval_festa/:id', to: 'avaliacao_festa#excluir'
end

app/models/festa.rb
class Festa < ActiveRecord::Base
  attr_accessor :current
  @connection = ActiveRecord::Base.establish_connection
  self.table_name = 'Festa'
  belongs_to :Balada
  # has_many:
end

app/controllers/festa_controller.rb
class FestaController < ApplicationController
  before_action :set_festa, only: [:show, :edit, :update, :destroy]

  # GET /festa
  # GET /festa.json
  # todas festas ativas
  def index
    @connection = ActiveRecord::Base.establish_connection
    sql = 'SELECT idFesta, nome, data, hora, tipo_bar, idBalada FROM Festa WHERE (data BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 100 DAY) && isActive = true) ORDER BY data ASC;'
    @festas = ActiveRecord::Base.connection.exec_query(sql)
  end

  # GET /festa/1
  # GET /festa/1.json
  def show
    @comentarios = comentarios(params[:id])
  end

  # GET /festa/new
  def new
    @festa = Festa.new
  end

  def search
    @nome = params[:festa] ? params[:festa] : ''
    @data_inicio = params[:data_inicio] ? params[:data_inicio] : Time.now.strftime('%Y-%m-%d')
    @data_fim = params[:data_fim] ? params[:data_fim] : (Time.now + 30.days).strftime('%Y-%m-%d')
    data_inicio = @data_inicio#.to_formatted_s(:db)
    data_fim = @data_fim#.to_formatted_s(:db)
    tipo_bar = if params[:tipo_bar] == 'Qualquer um' then'true || false'
              elsif params[:tipo_bar] == 'Open bar' then true
              else false
              end

    @connection = ActiveRecord::Base.establish_connection
    @sql = "SELECT idFesta, nome, data, hora, tipo_bar, idBalada
           FROM Festa
           WHERE(
            nome LIKE '%#{@nome}%' &&
            data BETWEEN '#{data_inicio}' AND '#{data_fim}' &&
            isActive = true
            ) ORDER BY data ASC;"# &&

            # BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 100 DAY &&
            # isActive = true)
          # ) ORDER BY data ASC;"
    @festas = ActiveRecord::Base.connection.exec_query(@sql)
  end

  # GET /festa/1/edit
  def edit
  end

  # POST /festa
  # POST /festa.json
  def create
    @festa = Festa.new(festa_params)

    respond_to do |format|
      if @festa.save
        format.html { redirect_to @festa, notice: 'Festa was successfully created.' }
        format.json { render :show, status: :created, location: @festa }
      else
        format.html { render :new }
        format.json { render json: @festa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /festa/1
  # PATCH/PUT /festa/1.json
  def update
    respond_to do |format|
      if @festa.update(festa_params)
        format.html { redirect_to @festa, notice: 'Festa was successfully updated.' }
        format.json { render :show, status: :ok, location: @festa }
      else
        format.html { render :edit }
        format.json { render json: @festa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /festa/1
  # DELETE /festa/1.json
  def destroy
    @festa.destroy
    respond_to do |format|
      format.html { redirect_to festa_url, notice: 'Festa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def comentarios(idFesta)
    @connection = ActiveRecord::Base.establish_connection
    sql = "SELECT * FROM AvaliacaoFesta WHERE idFesta = #{idFesta} AND isActive = true;"
    ActiveRecord::Base.connection.exec_query(sql)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_festa
      @connection = ActiveRecord::Base.establish_connection
      sql = "SELECT idFesta, nome, data, hora, tipo_bar, idBalada FROM Festa WHERE(idFesta = #{params[:id]} && isActive = true);"
      # @festa = Festa.find(params[:id])
      @festa = ActiveRecord::Base.connection.exec_query(sql)
      @festa = @festa.first.symbolize_keys!
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def festa_params
      params.fetch(:festa, {})
    end
end

app/helpers/festa_helper.rb
module FestaHelper
end

app/views/festa/_avaliacoes.html.erb
<% @comentarios.each do |comentario| %>
  <% comentario.symbolize_keys! %>
  <% if logged_in? %>
    <% if session[:idCadastro] == comentario[:idUsuario] %>
      <div class="row">
        <div class="col col-sm-7"></div>
          <div class="col col-sm-1">
            <a href="../excluir_aval_festa/<%= comentario[:idAvaliacao] %>"><span style="color:#A00" class="glyphicon glyphicon-remove"></span></a>
          </div>
        </div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col col-sm-6">
      <b><a href="../usuarios/<%= comentario[:idUsuario] %>"><%= nome_usuario(comentario[:idUsuario])[:nome] %></a></b>
      - <%= comentario[:dataHora].strftime('%d/%m/%Y às %H:%M') %>
    </div>
    <div class="col col-sm-6">
      <% (1..comentario[:nota]).each do %>
        <span class="glyphicon glyphicon-star"></span>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col col-sm-6">
      <%= comentario[:comentario] %>
    </div>
  </div>
  <hr />
<% end %>

app/views/festa/_avaliacoes_form.html.erb
<%= form_tag({ controller: 'avaliacao_festa', action: 'create' }, method: 'post') do %>
<div class="row">
  <div class="col col-sm-8"><b>O que achou da festa?</b></div>
  <div class="col col-sm-2"><b>Dê uma nota (1 a 5):</b></div>
</div>

<div class="row">
  <div class="col col-sm-8">
    <%= text_area_tag(:comentario, '', class: "form-control", style: 'resize: none;') %>
  </div>
  <div class="col col-sm-2">
    <div style="width:100px;">
      <%= select_tag(:nota, options_for_select([1, 2, 3, 4, 5]), { class: 'form-control' }) %><br />
      <%= hidden_field(:idFesta, :idFesta, :value => params[:id]) %>
      <div style="width: 100px;">
        <%= submit_tag('Enviar!', class: "form-control btn btn-sm btn-primary") %>
      </div>
    </div>
  </div>
</div>

<% end %>
<hr />

app/views/festa/_festas.html.erb
<div class="container marketing">
  <% i = 1 %>
  <% @festas.each do |festa| %>
    <% festa.symbolize_keys! %>
    <% if i%3 == 0 %><div class="row"><% end %>
      <div class="col-lg-4">
        <h2><a href="../festa/<%= festa[:idFesta] %>" style="color:#5F1B70;">Festa <%= festa[:nome] %></a></h2>
        <p><%= festa[:data].strftime('%d/%m/%Y') %> - <%= festa[:hora].strftime('%H:%M') %></p>
        <p>Na <%= info_balada(festa[:idBalada]) %></p>
        <p><% if festa[:tipo_bar] %>Open bar<% else %>Consumação<% end %></p>
      </div>
    <% if i%3 == 0 %></div><hr><% end %>
    <% i+=1%>
  <% end %>
</div>

app/views/festa/_form.html.erb
<%= form_for(festum) do |f| %>
  <% if festum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(festum.errors.count, "error") %> prohibited this festum from being saved:</h2>

      <ul>
      <% festum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/festa/_search_bar.html.erb
<%= form_tag({ controller: 'festa', action: 'search' }, method: 'get') do %>
  <div class="row">
    <div class="col col-md-4"><b>Nome da festa</b></div>
    <div class="col col-md-2"><b>De</b></div>
    <div class="col col-md-2"><b>Até</b></div>
    <div class="col col-md-2"><b>Tipo de bar</b></div>
  </div>
  <div class="row">
    <div class="col col-md-4">
      <%= text_field_tag(:festa, '', class: "form-control", placeholder: 'Nome da festa', value: @nome) %>
    </div>
    <div class="col col-md-2">
      <%= date_field_tag :data_inicio, 'Data inicial', class: "form-control", value: @data_inicio %>
    </div>
    <div class="col col-md-2">
      <%= date_field_tag :data_fim, 'Data inicial', class: "form-control", value: @data_fim %>
    </div>
    <div class="col col-md-2">
      <%= select_tag(:tipo_bar, options_for_select(['Qualquer um', 'Open bar', 'Consumação']), { class: 'form-control' }) %>
    </div>
    <div class="col col-md-1">
      <div style="width:50px;margin-left:50px">
        <%= button_tag(type: 'submit', class: "form-control btn-sm btn-primary") do %>
          <span class="glyphicon glyphicon-search"></span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/festa/edit.html.erb
<h1>Editing Festum</h1>

<%= render 'form', festum: @festum %>

<%= link_to 'Show', @festum %> |
<%= link_to 'Back', festa_path %>

app/views/festa/index.html.erb
<h1>Festas chegando:</h1>
<%= render 'festas' %>

app/views/festa/new.html.erb
<h1>New Festum</h1>

<%= render 'form', festum: @festum %>

<%= link_to 'Back', festa_path %>

app/views/festa/search.html.erb
<h2>Pesquisar festas:</h2>

<%= render 'search_bar' %>
<%= render 'festas' %>

app/views/festa/show.html.erb
<div class="row">
  <div class="col col-md-9"><h1>Festa <%= @festa[:nome] %></h1></div>
  <div class="col col-md-3"><br />
    <% if logged_in? %>
      <% if checked_in?(session[:idCadastro], params[:id]) %>
        <%= button_to 'Desfazer check-in', checkin_delete_path, method: :delete, class: 'btn btn-md btn-danger', params: { idFesta: params[:id] } %>
      <% else %>
        <%= button_to 'Check-in!', checkin_path, method: :post, class: 'btn btn-md btn-primary', params: { idFesta: params[:id] } %>
      <% end %>
      <% else %>
        <%= link_to 'Faça login e faça check-in!', login_path, class: 'btn btn-md btn-primary', style: 'color:#FFF' %>
    <% end %>
  </div>

</div>
<div class="row">
  <div class="col col-md-9">
  </div>
  <div class="col col-md-3">
    <%= qtd_checkin(params[:id]) %> pessoas estão aqui!
  </div>
</div>
<div class="row">
  <div class="col col-md-6">
    Quando: <b><%= @festa[:data].strftime('%d/%m/%Y') %> - <%= @festa[:hora].strftime('%H:%M') %></b>
  </div>
  <div class="col col-md-6">
    Onde: <b><a href="../baladas/<%= @festa[:idBalada] %>" style="color: #000;"><%= info_balada(@festa[:idBalada]) %></a></b>
  </div>
</div>
<div class="row">
  <div class="col col-md-6">
    Tipo de bar: <b><%= if @festa[:tipoBar] then 'Open' else 'Consumação' end %></b>
  </div>
  <div class="col col-md-6">
    Estilos:
    <b>
      <% estilo_festa(@festa[:idFesta]).each do |estilo| %>
       <%= estilo + ',' %>
      <% end %>
    </b>
  </div>
</div>
<div class="row">
  <div class="col col-md-6">
    Endereço:
  </div>
</div>

<hr />
<h3>Avaliações:</h3>
<% if logged_in? %>
  <%= render 'avaliacoes_form' %>
<% else %>
  <div class="row" style='margin-top:15px; margin-bottom:15px;'>
    <%= link_to 'Faça login para comentar', login_path, style: 'color:#337ab7;' %>
  </div>
<% end %>
<%= render 'avaliacoes' %>